service: trpc-lambda-esbuild
frameworkVersion: "3"

# クラウドプロバイダの設定
provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs16.x
  stage: dev
  timeout: 29

# デプロイ対象のファイルの指定
package:
  patterns:
    - "!**"
    - "node_modules/**"
    - "dist/**/*.js"

functions:
  # API Gateway v2
  http-api:
    handler: dist/index.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: any
  # API Gateway v1
  rest-api:
    handler: dist/index.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true
